namespace: default
clusterVPA:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 256Mi

podLabels:
  team: core
  provider: alibaba

castai:
  clusterID: "test"
  apiKeySecretRef: "some-secret"

tolerations:
  - key: scheduling.cast.ai/spot
    operator: Exists

aks:
  enabled: true
  nodeSelector:
    provisioner.cast.ai/aks-init-data: "true"
