namespace: default
clusterVPA:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 256Mi

podLabels:
  team: core
  provider: alibaba

castai:
  clusterID: "8192e3c9-bbe7-4afa-b364-7897b479a5b4"
  apiKey: "test"
  apiURL: "test"

tolerations:
  - key: scheduling.cast.ai/spot
    operator: Exists

commonLabels:
  label1: "label"

commonAnnotations:
  annotation1: "annotation"
