---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-controller-ext.fullname" . }}
  labels:
  {{- include "cluster-controller-ext.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
  {{- include "cluster-controller-ext.annotations" . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - volumeattachments
    verbs:
      - get
      - list
      - delete
